apiVersion: v1
kind: Secret
metadata:
  name: milvus-coredump-agent-secrets
  namespace: default
  labels:
    app: milvus-coredump-agent
type: Opaque
data:
  # Base64 encoded OpenAI API Key
  # To create: echo -n "your-openai-api-key" | base64
  openai-api-key: ""
---
# Alternative: Create the secret using kubectl command
# kubectl create secret generic milvus-coredump-agent-secrets \
#   --from-literal=openai-api-key=your-actual-api-key \
#   -n default