cluster:
  enabled: false

log:
  level: debug

image:
  all:
    repository: milvusdb/milvus
    tag: master-latest
    pullPolicy: Always
pulsarv3:
  enabled: false

pulsar:
  enabled: false

kafka:
  enabled: false
  name: kafka
  replicaCount: 3
  defaultReplicationFactor: 2

etcd:
  replicaCount: 3
  image:
    repository: milvusdb/etcd
    tag: 3.5.5-r2  
minio:
  mode: standalone
