apiVersion: v1
kind: Pod
metadata:
  name: milvus-test-crash
  labels:
    app.kubernetes.io/name: milvus
    helm.sh/chart: milvus
    app: milvus-test
spec:
  containers:
  - name: milvus
    image: alpine:3.18
    command: ["/bin/sh"]
    args: ["-c", "ulimit -c unlimited && echo 'Starting...' && timeout 10 /crasher || true && sleep 30"]
    volumeMounts:
    - name: coredump-test-volume
      mountPath: /crasher
      subPath: milvus_crasher
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - SYS_PTRACE
      runAsUser: 0
  volumes:
  - name: coredump-test-volume
    configMap:
      name: crash-test-program
      defaultMode: 0755
  restartPolicy: Always